name: risc-v-toolchains Build

on:
  push:
    branches:
      - main
jobs:
  risc-v-toolchains-build:
    name: risc-v-toolchains Build
    runs-on: ubuntu-latest
    steps:
      - name: Init
        run: |
          sudo apt-get install p7zip autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build
      - name: Init
        run: |
          git clone -depth=1 --recursive https://github.com/riscv/riscv-gnu-toolchain && cd riscv-gnu-toolchain
          ./configure --prefix="$PWD/opt-riscv/"
          make
      - name: Package Directories
        run: |
          7z a riscv-toolchains.7z ./riscv-gnu-toolchain/opt-riscv
      - uses: actions/upload-artifact@v3
        with:
          name: riscv-toolchains
          path: riscv-toolchains.7z
      # - name: Update Cpr Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: riscv-toolchains
      #     files: |
      #       riscv-toolchains.7z
